name: Build & Push Docker Images

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"    # pattern for v1.2.3
      - "v[0-9]*.[0-9]*.[0-9]*-*"  # pattern for v1.2.3-suffix

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Determine Version
        id: tag_info
        run: |
          TAG="${GITHUB_REF_NAME}"
          echo "Tag: $TAG"

          if [[ "$TAG" =~ ^v([0-9]+\.[0-9]+\.[0-9]+.*)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
          else
            echo "::error::unrecognized tag format $TAG"
            exit 1
          fi

          echo "::notice::evaluated version $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')  # only login when we intend to push (i.e. tag builds)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # failbook-builder:latest image is used as FROM in main Dockerfile
      - name: Build failbook-builder:latest Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.builder
          push: false
          tags: failbook-builder:latest

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/') }}  # true on tag, false on branch
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/failbook:${{ steps.tag_info.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/failbook:latest
